import Head from 'next/head'
import { useState } from 'react';
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import HomePage from './homePage';
import UserData from './userData';
import Market from './market';

// const ContractAddress = "0x4ff9EB4C5F5f790CE7bB51d4876481C2eefDE00F"; // MUMBAI NETWORK      

export default function Home() {

  const [currentPage, setCurrentPage] = useState("home");



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar onLinkClick={setCurrentPage} />{" "}
      <main
        className={styles.main}
        style={{
          background: "linear-gradient(170deg, #003366, #0066CC, #99D1FF)",
        }}
      >
        <div className={styles.description}>
          {currentPage === "home" && <HomePage />}
          {currentPage === "userData" && <UserData />}
          {currentPage === "market" && <Market/>}
        </div>
      </main>
    </>
  );
}
